apiVersion: v1
kind: Service
metadata:
  labels:
    app: service-kbn-compile-triton-vllm-server
  name: service-kbn-compile-triton-vllm-server
  namespace: triton-inference
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: http
    - name: grpc
      protocol: TCP
      port: 8001
      targetPort: grpc
    - name: metrics
      protocol: TCP
      port: 8002
      targetPort: metrics
    - name: windsurf-server
      protocol: TCP
      port: 42435
      targetPort: windsurf-server
    - name: ssh
      protocol: TCP
      port: 5678
      targetPort: 22
  selector:
    app: kbn-compile-triton-vllm-server
  sessionAffinity: None
  type: NodePort